hx:
  oauth2:
    client:
      # jwt的密钥
      signingKey: hxmec
      resourceId: ${spring.application.name}
      # 放行的url
      ignoreUrls:
        - /oauth/**
        - /user/**



#ribbon全局配置
ribbon:
  #处理请求的超时时间，单位ms，默认1000
  ReadTimeout: 3000
  #连接建立的超时时间，单位ms，默认1000
  ConnectTimeout: 3000

feign:
  compression:
    request:
      #是否启用请求GZIP压缩，true：启用，false：不启用
      enabled: true
      #压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      #压缩数据的最小值
      min-request-size: 2048
    response:
      #是否启用响应GZIP压缩，true：启用，false：不启用
      enabled: true
  client:
    config:
      #feign全局配置
      default:
        #指定日志级别，none：不记录任何日志，basic：仅记录请求方法、URL、响应状态代码以及执行时间（适合生产环境）
        #headers：在basic基础上，记录请求和响应的header，full：记录请求和响应的header、body和元数据，默认none
        loggerLevel: basic
      #feign指定客户端配置，即仅对指定调用的服务生效
      eureka-client:
        loggerLevel: full
